### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by jhoetter** [yobulkdev/yobulkdev#104]
Hi YoBulk team,

was hoping for someone to build an open-source CSV file import for some time now, so really was excited to see this.

I have a small issue with the installation. This can be me doing something absolutely dumb, but I thought to share it here since I followed the installation guide and ran into errors.

After cloning and moving into the repo, running the `docker-compose up -d` results in:
```
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 670, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 439, in send
  File "urllib3/connectionpool.py", line 726, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 670, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 60, in project_from_options
  File "compose/cli/command.py", line 152, in get_project
  File "compose/cli/docker_client.py", line 41, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 221, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

Really not a Docker expert here, so can be absolutely my fault :) Do you have any ideas? (FileNotFound always seems to me like some part of the docker compose could have gone wrong?)

**Comment by samurai2y** [comment]
Hi @jhoetter, if you are using docker on windows, make sure the docker daemon is up. This error can come when the docker daemon is not running.

You can check whether the docker daemon is up or not by running the command: `docker version`

If it says that docker daemon is not running, then you need to start it (generally by starting docker desktop) and then run `docker compose up -d`

**Comment by YoBulkMaster** [comment]
@jhoetter kindly try `sudo docker-compose up -d`. Would be eager to catch up if issue still persists. Thanks for trying this.

**Comment by jhoetter** [comment]
@samurai2y running this on macOS Ventura 13.2.1
@YoBulkMaster still the output mentioned above

**Comment by samurai2y** [comment]
@jhoetter did `docker version` show the warning that the docker daemon is not running?

**Comment by jhoetter** [comment]
arghh super sorry, i have no idea why on earth it wasn't running, but that was the solution. So yeah, that's 100% on me. It's pulling now, happy to check it out. looks amazing.
